repositories:
- name: prometheus
  url: https://prometheus-community.github.io/helm-charts
releases:
- name: prometheus
  namespace: prometheus
  chart: prometheus/prometheus
  set:
  - name: rbac.create
    value: false
- name: devops-toolkit
  namespace: production
  chart: devops-toolkit
  set:
  - name: image.tag
    value: "2.9.10"
  - name: ingress.host
    value: devops-toolkit.{{ requiredEnv "BASE_HOST" }}
- name: devops-paradox
  namespace: production
  chart: devops-paradox
  set:
  - name: image.tag
    value: "1.71"
  - name: ingress.host
    value: {{ env "DEVOPS_PARADOX_HOST" | default "devops-paradox.acme.com" }}
