---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: 80
    host: {{ .Values.ingress.host }}
